# Site settings
title: Schuyler

avatar: https://github.com/schuyler-smith.png
page_icon: https://github.com/schuyler-smith.png

name: Schuyler D. Smith
description: Ph.D. Student - Bioinformatics and Computational Biology


